Guess who got caught?
Who?
NullPointerException.
Seriously?
No. Finally.
